name: Build and Push Docker Image to Azure ACR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      #ACR_REPO_NAME: "${{ github.event.repository.name }}"
      ACR_REPO_NAME: "coffeeshop"
       
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
    - name: Print env variables
      run: |
        echo "ACR_REPO_NAME=${ACR_REPO_NAME}"
        echo "${ACR_REPO_NAME}.azurecr.io"
        echo "$ACR_REPO_NAME"
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: "coffeeshop.azurecr.io"
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t coffeeshop.azurecr.io/coffeeshop:${GITHUB_RUN_NUMBER} .
        docker push coffeeshop.azurecr.io/coffeeshop:${GITHUB_RUN_NUMBER}